# Generated by Django 3.2 on 2023-04-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('date_supplied', models.DateTimeField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, max_length=6)),
                ('expiry_date', models.DateTimeField(max_length=255)),
                ('strength', models.CharField(max_length=255)),
            ],
        ),
    ]
