# Generated by Django 3.2 on 2023-04-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='quantity',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
