# Generated by Django 3.2 on 2023-04-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_drug_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
