# Generated by Django 3.2 on 2023-04-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_alter_drug_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='date_supplied',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='drug',
            name='expiry_date',
            field=models.DateField(max_length=255),
        ),
    ]
