# Generated by Django 3.2 on 2023-03-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('employee_code', models.CharField(max_length=255)),
                ('personal_email', models.CharField(max_length=255)),
                ('work_email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('employment_type', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
            ],
        ),
    ]
