# Generated by Django 3.2 on 2023-03-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
