# Generated by Django 3.2 on 2023-04-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe_management', '0004_employee_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='rate_per_hour',
        ),
        migrations.AddField(
            model_name='employee',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
